services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NEXT_PUBLIC_BACKEND_BASE: "http://host.docker.internal:8080"
      API_TOKEN: "my-secret-token"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: npm run dev

volumes:
  node_modules:
