services:
  frontend:
    container_name: beerbot_frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      NEXT_PUBLIC_BACKEND_BASE: "http://localhost:8080"
      API_TOKEN: "my-secret-token"
    ports:
      - "3000:3000"
    command: bun run start
