name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.0'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type check
        run: bunx tsc --noEmit

      - name: Run lint
        run: bun run lint

      - name: Build application
        run: bun run build

      - name: Check for security vulnerabilities
        run: bun audit --audit-level high